name: docs_pages_workflow

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB-PAT: ${{ secrets.GITHUB.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run:
          pip install -U sphinx
          pip install myst_parser

      - name: Make Sphinx Docs
        run:
          make html
      
      - name: Init new repo and commit
        run:
          cd build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "thetreeholepost@gmail.com"
          git config --local user.name "treeholepost"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB.TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build/html/
